/**
 * GENERATED by scripts/generate-untrusted-confusables.ts — do not edit by hand.
 *
 * Source: Unicode UTS #39 confusables.txt 17.0.0 (2025-07-22); UnicodeData.txt small-capital names.
 * 674 letter/digit entries (16 small capitals from UnicodeData names), 64 delimiter entries.
 *
 * Each entry is a folded non-ASCII code point (NFKC, NFD, combining marks
 * dropped) followed by the ASCII it is confusable with; entries are separated
 * by one space. Parsed by untrusted-text-matching.ts.
 */

export const CONFUSABLES_SOURCE = 'Unicode UTS #39 confusables.txt 17.0.0 (2025-07-22); UnicodeData.txt small-capital names';

/** Non-ASCII code point → ASCII letters/digits (UTS #39 prototype, marks removed). */
export const LETTER_CONFUSABLE_ENTRIES =
  '\u{A2}c \u{A5}Y \u{C6}AE \u{D0}D \u{D7}x \u{D8}O \u{E6}ae \u{F8}o \u{FE}p \u{110}D \u{111}d ' +
  '\u{126}H \u{127}h \u{141}L \u{142}l \u{14B}n \u{152}OE \u{153}oe \u{166}T \u{167}t \u{180}b ' +
  '\u{182}b \u{183}b \u{184}b \u{189}D \u{18C}d \u{18D}g \u{191}F \u{192}f \u{196}l \u{197}l ' +
  '\u{199}k \u{19A}l \u{19D}N \u{19E}n \u{19F}O \u{1A5}p \u{1A6}R \u{1A7}2 \u{1AD}t \u{1AE}T ' +
  '\u{1B4}y \u{1B5}Z \u{1B6}z \u{1B7}3 \u{1BB}2 \u{1BC}5 \u{1BD}s \u{1BF}p \u{1C0}l \u{1C1}ll ' +
  '\u{1E4}G \u{1E5}g \u{21C}3 \u{222}8 \u{223}8 \u{224}Z \u{225}z \u{23C}c \u{23E}T \u{244}U ' +
  '\u{246}E \u{247}e \u{248}J \u{249}j \u{24D}r \u{24E}Y \u{24F}y \u{251}a \u{253}b \u{256}d ' +
  '\u{257}d \u{260}g \u{261}g \u{262}G \u{263}y \u{266}h \u{268}i \u{269}i \u{26A}i \u{26B}l ' +
  '\u{26D}l \u{26F}w \u{271}rn \u{273}n \u{274}N \u{275}o \u{27C}r \u{27D}r \u{280}R \u{282}s ' +
  '\u{28B}u \u{28F}y \u{290}z \u{299}B \u{29C}H \u{29F}L \u{2A0}q \u{2A3}dz \u{2A6}ts \u{2A9}fn ' +
  '\u{2AA}ls \u{2AB}lz \u{37F}J \u{391}A \u{392}B \u{395}E \u{396}Z \u{397}H \u{398}O \u{399}l ' +
  '\u{39A}K \u{39C}M \u{39D}N \u{39F}O \u{3A1}P \u{3A3}C \u{3A4}T \u{3A5}Y \u{3A7}X \u{3B1}a ' +
  '\u{3B3}y \u{3B7}n \u{3B8}O \u{3B9}i \u{3BD}v \u{3BF}o \u{3C1}p \u{3C2}c \u{3C3}o \u{3C5}u ' +
  '\u{3DC}F \u{3E8}2 \u{3EC}6 \u{3ED}o \u{3F3}j \u{3F8}p \u{3FA}M \u{405}S \u{406}l \u{408}J ' +
  '\u{410}A \u{411}b \u{412}B \u{415}E \u{417}3 \u{41A}K \u{41C}M \u{41D}H \u{41E}O \u{420}P ' +
  '\u{421}C \u{422}T \u{423}Y \u{425}X \u{42B}bl \u{42C}b \u{42E}lO \u{430}a \u{431}6 \u{433}r ' +
  '\u{435}e \u{43D}H \u{43E}o \u{440}p \u{441}c \u{443}y \u{445}x \u{448}w \u{455}s \u{456}i ' +
  '\u{458}j \u{45B}h \u{45F}u \u{461}w \u{462}b \u{463}b \u{472}O \u{473}o \u{474}V \u{475}v ' +
  '\u{47D}w \u{48C}b \u{48D}b \u{493}r \u{498}3 \u{49A}K \u{49E}K \u{4A2}H \u{4AA}C \u{4AB}c ' +
  '\u{4AC}T \u{4AE}Y \u{4AF}y \u{4B0}Y \u{4B1}y \u{4B2}X \u{4BB}h \u{4BD}e \u{4BF}e \u{4C0}l ' +
  '\u{4C7}H \u{4C9}H \u{4CD}M \u{4CF}l \u{4D4}AE \u{4D5}ae \u{4E0}3 \u{4E8}O \u{4E9}o \u{501}d ' +
  '\u{50C}G \u{51B}q \u{51C}W \u{51D}w \u{54D}U \u{54F}S \u{555}O \u{561}w \u{563}q \u{566}q ' +
  '\u{570}h \u{572}n \u{578}n \u{57C}n \u{57D}u \u{581}g \u{582}i \u{584}f \u{585}o \u{5C0}l ' +
  '\u{5D5}l \u{5D8}v \u{5DF}l \u{5E1}o \u{5F0}ll \u{627}l \u{647}o \u{661}l \u{665}o \u{667}V ' +
  '\u{673}l \u{6BE}o \u{6C1}o \u{6D5}o \u{6F1}l \u{6F5}o \u{6F7}V \u{6FF}o \u{7C0}O \u{7CA}l ' +
  '\u{966}o \u{969}3 \u{9E6}o \u{9EA}8 \u{9ED}9 \u{A66}o \u{A67}9 \u{A6A}8 \u{AE6}o \u{AE9}3 ' +
  '\u{B20}O \u{B66}o \u{B68}9 \u{BE6}o \u{C66}o \u{CE6}O \u{D1F}s \u{D20}o \u{D66}o \u{D6D}9 ' +
  '\u{E50}o \u{ED0}o \u{1004}c \u{1010}o \u{101D}o \u{1040}o \u{105A}c \u{10D7}o \u{10E7}y ' +
  '\u{10FF}o \u{1200}U \u{12D0}O \u{13A0}D \u{13A1}R \u{13A2}T \u{13A5}i \u{13A9}Y \u{13AA}A ' +
  '\u{13AB}J \u{13AC}E \u{13B3}W \u{13B7}M \u{13BB}H \u{13BD}Y \u{13BE}O \u{13C0}G \u{13C2}h ' +
  '\u{13C3}Z \u{13CC}U \u{13CE}4 \u{13CF}b \u{13D2}R \u{13D4}W \u{13D5}S \u{13D9}V \u{13DA}S ' +
  '\u{13DE}L \u{13DF}C \u{13E2}P \u{13E6}K \u{13E7}d \u{13EB}O \u{13EE}6 \u{13F2}h \u{13F3}G ' +
  '\u{13F4}B \u{142F}V \u{144C}U \u{146D}P \u{146F}d \u{1472}b \u{1473}b \u{148D}J \u{14AA}L ' +
  '\u{14BF}2 \u{1541}x \u{157C}H \u{157D}x \u{1587}R \u{15AF}b \u{15B4}F \u{15C5}A \u{15DE}D ' +
  '\u{15EA}D \u{15F0}M \u{15F7}B \u{166D}X \u{166E}x \u{16B7}X \u{16C1}l \u{16D5}K \u{16D6}M ' +
  '\u{17E0}o \u{1D00}A \u{1D04}c \u{1D05}D \u{1D07}E \u{1D0A}J \u{1D0B}K \u{1D0D}M \u{1D0F}o ' +
  '\u{1D11}o \u{1D18}P \u{1D1B}T \u{1D1C}u \u{1D20}v \u{1D21}w \u{1D22}z \u{1D26}r \u{1D6B}ue ' +
  '\u{1D6E}f \u{1D6F}rn \u{1D70}n \u{1D72}r \u{1D74}s \u{1D75}t \u{1D76}z \u{1D7B}i \u{1D7C}i ' +
  '\u{1D7D}p \u{1D7E}u \u{1D83}g \u{1D8C}y \u{1E9D}f \u{1EFF}y \u{2016}ll \u{20A1}C \u{20A5}rn ' +
  '\u{20A9}W \u{20AB}d \u{20AD}K \u{20AE}T \u{20B6}lt \u{212E}e \u{221E}oo \u{2223}l \u{2225}ll ' +
  '\u{2228}v \u{222A}U \u{2296}O \u{229D}O \u{22A4}T \u{22C1}v \u{22C3}U \u{22FF}E \u{2361}T ' +
  '\u{236C}O \u{2373}i \u{2374}p \u{2376}a \u{2378}i \u{237A}a \u{23E8}10 \u{23FD}l \u{2502}l ' +
  '\u{2573}X \u{27D9}T \u{292B}x \u{292C}x \u{2A2F}x \u{2A30}x \u{2C67}H \u{2C69}K \u{2C82}B ' +
  '\u{2C85}r \u{2C8E}H \u{2C90}O \u{2C91}o \u{2C92}l \u{2C93}i \u{2C94}K \u{2C98}M \u{2C9A}N ' +
  '\u{2C9C}3 \u{2C9E}O \u{2C9F}o \u{2CA2}P \u{2CA3}p \u{2CA4}C \u{2CA5}c \u{2CA6}T \u{2CA8}Y ' +
  '\u{2CA9}y \u{2CAC}X \u{2CBD}w \u{2CC4}3 \u{2CCA}9 \u{2CCB}9 \u{2CCC}3 \u{2CCE}P \u{2CCF}p ' +
  '\u{2CD0}L \u{2CD2}6 \u{2CD3}6 \u{2CDC}6 \u{2D31}O \u{2D38}V \u{2D39}E \u{2D41}O \u{2D4F}l ' +
  '\u{2D54}O \u{2D55}Q \u{2D5D}X \u{3007}O \u{A4D0}B \u{A4D1}P \u{A4D2}d \u{A4D3}D \u{A4D4}T ' +
  '\u{A4D6}G \u{A4D7}K \u{A4D9}J \u{A4DA}C \u{A4DC}Z \u{A4DD}F \u{A4DF}M \u{A4E0}N \u{A4E1}L ' +
  '\u{A4E2}S \u{A4E3}R \u{A4E6}V \u{A4E7}H \u{A4EA}W \u{A4EB}X \u{A4EC}Y \u{A4EE}A \u{A4F0}E ' +
  '\u{A4F2}l \u{A4F3}O \u{A4F4}U \u{A644}2 \u{A647}i \u{A695}h \u{A698}OO \u{A699}oo \u{A6DF}V ' +
  '\u{A6EF}2 \u{A728}T3 \u{A730}F \u{A731}s \u{A732}AA \u{A733}aa \u{A734}AO \u{A735}ao \u{A736}AU ' +
  '\u{A737}au \u{A738}AV \u{A739}av \u{A73A}AV \u{A73B}av \u{A73C}AY \u{A73D}ay \u{A740}K ' +
  '\u{A74A}O \u{A74B}o \u{A74E}OO \u{A74F}oo \u{A75A}2 \u{A761}w \u{A76A}3 \u{A76E}9 \u{A777}tf ' +
  '\u{A798}F \u{A799}f \u{A79F}u \u{A7AB}3 \u{A7AF}Q \u{A7B2}J \u{A7B3}X \u{A7B4}B \u{AB32}e ' +
  '\u{AB35}f \u{AB3D}o \u{AB3E}o \u{AB47}r \u{AB48}r \u{AB4E}u \u{AB52}u \u{AB5A}y \u{AB63}uo ' +
  '\u{AB74}o \u{AB75}i \u{AB81}r \u{AB83}w \u{AB8E}o \u{AB93}z \u{AB9C}u \u{ABA9}v \u{ABAA}s ' +
  '\u{ABAF}c \u{ABBB}o \u{1018E}N \u{10196}X \u{10197}V \u{10198}llS \u{10199}ll \u{10282}B ' +
  '\u{10286}E \u{10287}F \u{1028A}l \u{10290}X \u{10292}O \u{10295}P \u{10296}S \u{10297}T ' +
  '\u{102A0}A \u{102A1}B \u{102A2}C \u{102A5}F \u{102AB}O \u{102B0}M \u{102B1}T \u{102B2}Y ' +
  '\u{102B4}X \u{102CF}H \u{102F5}Z \u{10301}B \u{10302}C \u{10309}l \u{10311}M \u{10315}T ' +
  '\u{10317}X \u{1031A}8 \u{10320}l \u{10322}X \u{10404}O \u{10415}C \u{1041B}L \u{10420}S ' +
  '\u{1042C}o \u{1043D}c \u{10448}s \u{104B4}R \u{104C2}O \u{104CE}U \u{104D2}7 \u{104EA}o ' +
  '\u{104F6}u \u{10513}N \u{10516}O \u{10518}K \u{1051C}C \u{1051D}V \u{10525}F \u{10526}L ' +
  '\u{10527}X \u{114C5}w \u{114D0}o \u{11700}rn \u{11706}v \u{1170A}w \u{1170E}w \u{1170F}w ' +
  '\u{118A0}V \u{118A2}F \u{118A3}L \u{118A4}Y \u{118A6}E \u{118A9}Z \u{118AC}9 \u{118AE}E ' +
  '\u{118AF}4 \u{118B2}L \u{118B5}O \u{118B8}U \u{118BB}5 \u{118BC}T \u{118C0}v \u{118C1}s ' +
  '\u{118C2}F \u{118C3}i \u{118C4}z \u{118C6}7 \u{118C8}o \u{118CA}3 \u{118CC}9 \u{118D5}6 ' +
  '\u{118D6}9 \u{118D7}o \u{118D8}u \u{118DC}y \u{118E0}O \u{118E3}rn \u{118E5}Z \u{118E6}W ' +
  '\u{118E9}C \u{118EC}X \u{118EF}W \u{118F2}C \u{11DDA}l \u{11DE0}O \u{11DE1}l \u{16EAA}l ' +
  '\u{16EB6}b \u{16F08}V \u{16F0A}T \u{16F16}L \u{16F28}l \u{16F35}R \u{16F3A}S \u{16F3B}3 ' +
  '\u{16F40}A \u{16F42}U \u{16F43}Y \u{1D206}3 \u{1D20D}V \u{1D212}7 \u{1D213}F \u{1D216}R ' +
  '\u{1D21A}O \u{1D22A}L \u{1E8C7}l \u{1E8CB}8 \u{1F16E}C \u{1F700}QE \u{1F707}AR \u{1F708}V ' +
  '\u{1F714}O \u{1F74C}C \u{1F75C}sss \u{1F768}T \u{1F76B}MB \u{1F76C}VB ';

/** Non-ASCII code point → one of `<>[]/=()-` (UTS #39 prototype). */
export const DELIMITER_CONFUSABLE_ENTRIES =
  '\u{2C2}< \u{2C3}> \u{2D7}- \u{6D4}- \u{1400}= \u{1433}> \u{1438}< \u{16B2}< \u{1735}/ \u{2010}- ' +
  '\u{2012}- \u{2013}- \u{2014}- \u{2039}< \u{203A}> \u{2041}/ \u{2043}- \u{2044}/ \u{2212}- ' +
  '\u{2215}/ \u{2238}- \u{2250}= \u{2251}= \u{2257}= \u{2259}= \u{225A}= \u{225E}= \u{2571}/ ' +
  '\u{2768}( \u{2769}) \u{276E}< \u{276F}> \u{2772}( \u{2773}) \u{2796}- \u{27CB}/ \u{29F6}/ ' +
  '\u{29F8}/ \u{2A29}- \u{2A2A}- \u{2A6E}= \u{2B96}= \u{2CB2}- \u{2CB3}- \u{2CBA}- \u{2CBB}- ' +
  '\u{2CC6}/ \u{2CC7}/ \u{2E1A}- \u{2E40}= \u{3014}( \u{3015}) \u{3033}/ \u{30A0}= \u{30CE}/ ' +
  '\u{31D3}/ \u{4E3F}/ \u{A4FF}= \u{FD3E}( \u{FD3F}) \u{16F3F}> \u{1D236}< \u{1D237}> \u{1D23A}/ ';
