/**
 * Minimal seed for the e2e/journeys/* suite.
 *
 * Inserts (idempotent on the QA_JOURNEY_SEED_PREFIX):
 *   - 2 tenants  (Tenant A, Tenant B)
 *   - 3 customers per tenant
 *   - 1 service location per tenant (jobs require location_id)
 *   - 2 jobs per tenant
 *   - 2 estimates per tenant
 *   - 2 appointments per tenant
 *
 * Reads DATABASE_URL (typically set by setupTestDb in globalSetup). Refuses
 * to run if the URL looks like production.
 *
 * Two entry points:
 *   - `seedJourneyFixtures()` — async function imported by Playwright
 *     globalSetup. Returns the seeded IDs as an object AND writes the
 *     env file. Caller can hydrate process.env from the return value
 *     to avoid the env-file round-trip if it prefers.
 *   - `main()` — CLI wrapper for stand-alone use.
 *
 * Output:
 *   stdout: `export E2E_TENANT_A_ID=…` lines (paste-into-shell shape, same
 *           as e2e/qa-matrix/fixtures/seed.ts)
 *   file:   e2e/fixtures/.journey-fixtures.env — keyed env file for
 *           Playwright globalSetup to load via dotenv
 *
 * Flags:
 *   --dry-run    print what it would insert without connecting
 */
import { randomUUID } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { Client } from 'pg';
import { checkDatabaseUrlSafety, exitIfUnsafe } from './safety';

const FIXTURES_DIR = resolve(process.cwd(), 'e2e', 'fixtures');
const ENV_FILE = join(FIXTURES_DIR, '.journey-fixtures.env');

interface TenantFixture {
  tenantId: string;
  customerIds: string[];
  jobIds: string[];
  estimateIds: string[];
  appointmentIds: string[];
}

export interface JourneyFixtures {
  envFilePath: string;
  envVars: Record<string, string>;
  tenantA: TenantFixture;
  tenantB: TenantFixture;
}

/**
 * In-process seed. Used by Playwright globalSetup so the seeded IDs
 * can be applied directly to process.env without an env-file round-trip
 * (the file is still written for human use / re-runs).
 */
export async function seedJourneyFixtures(opts: { connectionString?: string } = {}): Promise<JourneyFixtures> {
  const connectionString = opts.connectionString ?? process.env.DATABASE_URL;
  const decision = checkDatabaseUrlSafety(connectionString);
  exitIfUnsafe(decision);

  const prefix = process.env.QA_JOURNEY_SEED_PREFIX ?? 'qa-journey';
  const client = new Client({
    connectionString,
    ssl: shouldUseSsl(connectionString ?? '') ? { rejectUnauthorized: false } : undefined,
  });
  await client.connect();
  try {
    const a = await ensureTenantFixture(client, `${prefix}-A`);
    const b = await ensureTenantFixture(client, `${prefix}-B`);

    const envVars: Record<string, string> = {
      E2E_TENANT_A_ID: a.tenantId,
      E2E_TENANT_A_CUSTOMER_ID: a.customerIds[0],
      E2E_TENANT_A_CUSTOMER_IDS: a.customerIds.join(','),
      E2E_TENANT_A_JOB_ID: a.jobIds[0],
      E2E_TENANT_A_JOB_IDS: a.jobIds.join(','),
      E2E_TENANT_A_ESTIMATE_ID: a.estimateIds[0],
      E2E_TENANT_A_ESTIMATE_IDS: a.estimateIds.join(','),
      E2E_TENANT_A_APPOINTMENT_ID: a.appointmentIds[0],
      E2E_TENANT_A_APPOINTMENT_IDS: a.appointmentIds.join(','),
      E2E_TENANT_B_ID: b.tenantId,
      E2E_TENANT_B_CUSTOMER_ID: b.customerIds[0],
      E2E_TENANT_B_CUSTOMER_IDS: b.customerIds.join(','),
      E2E_TENANT_B_JOB_ID: b.jobIds[0],
      E2E_TENANT_B_JOB_IDS: b.jobIds.join(','),
      E2E_TENANT_B_ESTIMATE_ID: b.estimateIds[0],
      E2E_TENANT_B_ESTIMATE_IDS: b.estimateIds.join(','),
      E2E_TENANT_B_APPOINTMENT_ID: b.appointmentIds[0],
      E2E_TENANT_B_APPOINTMENT_IDS: b.appointmentIds.join(','),
    };

    const fileLines = [
      `# Auto-generated by e2e/fixtures/seed-journey-fixtures.ts at ${new Date().toISOString()}`,
      ...Object.entries(envVars).map(([k, v]) => `${k}=${v}`),
      '',
    ];
    writeFileSync(ENV_FILE, fileLines.join('\n'));

    return { envFilePath: ENV_FILE, envVars, tenantA: a, tenantB: b };
  } finally {
    await client.end();
  }
}

async function ensureTenantFixture(client: Client, slug: string): Promise<TenantFixture> {
  const systemUser = 'qa-journey-seeder';
  const ownerId = `qa-journey:${slug}`;
  const ownerEmail = `${slug}@qa.serviceos.local`;

  // Tenant
  const tenantRes = await client.query(
    `SELECT id FROM tenants WHERE owner_id = $1 LIMIT 1`,
    [ownerId]
  );
  const tenantId =
    tenantRes.rows[0]?.id ??
    (
      await client.query(
        `INSERT INTO tenants (id, owner_id, owner_email, name, created_at, updated_at)
         VALUES ($1, $2, $3, $4, now(), now())
         RETURNING id`,
        [randomUUID(), ownerId, ownerEmail, `QA Journey ${slug}`]
      )
    ).rows[0].id;

  // Customers (3)
  const customerIds: string[] = [];
  for (let i = 1; i <= 3; i++) {
    const display = `${slug}-customer-${i}`;
    const existing = await client.query(
      `SELECT id FROM customers WHERE tenant_id = $1 AND display_name = $2 LIMIT 1`,
      [tenantId, display]
    );
    const cid =
      existing.rows[0]?.id ??
      (
        await client.query(
          `INSERT INTO customers
             (id, tenant_id, first_name, last_name, display_name, primary_phone, preferred_channel,
              sms_consent, is_archived, created_by, created_at, updated_at)
           VALUES ($1, $2, $3, $4, $5, $6, 'none', false, false, $7, now(), now())
           RETURNING id`,
          [randomUUID(), tenantId, 'QA', `${slug}-${i}`, display, `555-010${i}`, systemUser]
        )
      ).rows[0].id;
    customerIds.push(cid);
  }

  // Service location (1) — needed because jobs require location_id.
  const locationLabel = `${slug}-location`;
  const locExisting = await client.query(
    `SELECT id FROM service_locations WHERE tenant_id = $1 AND customer_id = $2 AND label = $3 LIMIT 1`,
    [tenantId, customerIds[0], locationLabel]
  );
  const locationId =
    locExisting.rows[0]?.id ??
    (
      await client.query(
        `INSERT INTO service_locations
           (id, tenant_id, customer_id, label, street1, city, state, postal_code, country, created_at, updated_at)
         VALUES ($1, $2, $3, $4, '1 QA Way', 'Testville', 'CA', '90001', 'US', now(), now())
         RETURNING id`,
        [randomUUID(), tenantId, customerIds[0], locationLabel]
      )
    ).rows[0].id;

  // Jobs (2)
  const jobIds: string[] = [];
  for (let i = 1; i <= 2; i++) {
    const jobNumber = `${slug}-job-${i}`;
    const existing = await client.query(
      `SELECT id FROM jobs WHERE tenant_id = $1 AND job_number = $2 LIMIT 1`,
      [tenantId, jobNumber]
    );
    const jid =
      existing.rows[0]?.id ??
      (
        await client.query(
          `INSERT INTO jobs
             (id, tenant_id, customer_id, location_id, job_number, summary, status, priority, created_by,
              created_at, updated_at)
           VALUES ($1, $2, $3, $4, $5, $6, 'new', 'normal', $7, now(), now())
           RETURNING id`,
          [randomUUID(), tenantId, customerIds[0], locationId, jobNumber, `QA journey job ${i} for ${slug}`, systemUser]
        )
      ).rows[0].id;
    jobIds.push(jid);
  }

  // Estimates (2) — one per job. Unique by (tenant_id, estimate_number).
  const estimateIds: string[] = [];
  for (let i = 0; i < 2; i++) {
    const number = `${slug}-est-${i + 1}`;
    const existing = await client.query(
      `SELECT id FROM estimates WHERE tenant_id = $1 AND estimate_number = $2 LIMIT 1`,
      [tenantId, number]
    );
    const eid =
      existing.rows[0]?.id ??
      (
        await client.query(
          `INSERT INTO estimates
             (id, tenant_id, job_id, estimate_number, status,
              subtotal_cents, taxable_subtotal_cents, tax_cents, total_cents,
              created_by, created_at, updated_at)
           VALUES ($1, $2, $3, $4, 'draft', 10000, 10000, 0, 10000, $5, now(), now())
           RETURNING id`,
          [randomUUID(), tenantId, jobIds[i], number, systemUser]
        )
      ).rows[0].id;
    estimateIds.push(eid);
  }

  // Appointments (2). Schema requires job_id + scheduled_{start,end} + timezone.
  const appointmentIds: string[] = [];
  for (let i = 0; i < 2; i++) {
    // Idempotency via notes column (no obvious unique key on appointments).
    const note = `qa-journey:${slug}:appt-${i + 1}`;
    const existing = await client.query(
      `SELECT id FROM appointments WHERE tenant_id = $1 AND notes = $2 LIMIT 1`,
      [tenantId, note]
    );
    const aid =
      existing.rows[0]?.id ??
      (
        await client.query(
          `INSERT INTO appointments
             (id, tenant_id, job_id, scheduled_start, scheduled_end, timezone, status,
              notes, created_by, created_at, updated_at)
           VALUES ($1, $2, $3, now() + ($4 || ' hours')::interval, now() + ($5 || ' hours')::interval,
                   'America/Los_Angeles', 'scheduled', $6, $7, now(), now())
           RETURNING id`,
          [randomUUID(), tenantId, jobIds[i], String(24 + i * 24), String(26 + i * 24), note, systemUser]
        )
      ).rows[0].id;
    appointmentIds.push(aid);
  }

  return { tenantId, customerIds, jobIds, estimateIds, appointmentIds };
}

function shouldUseSsl(connectionString: string): boolean {
  return /railway|rlwy|supabase|amazonaws|heroku/i.test(connectionString);
}

const isDryRun = process.argv.includes('--dry-run');

async function main(): Promise<void> {
  if (isDryRun) {
    console.log('[seed-journey] --dry-run — no DB connection.');
    console.log('[seed-journey] would seed 2 tenants × {3 customers, 2 jobs, 2 estimates, 2 appointments}.');
    console.log(`[seed-journey] would write env file: ${ENV_FILE}`);
    console.log('[seed-journey] sample export lines:');
    for (const label of ['A', 'B'] as const) {
      console.log(`  export E2E_TENANT_${label}_ID=<uuid>`);
      console.log(`  export E2E_TENANT_${label}_CUSTOMER_ID=<uuid>`);
      console.log(`  export E2E_TENANT_${label}_JOB_ID=<uuid>`);
      console.log(`  export E2E_TENANT_${label}_ESTIMATE_ID=<uuid>`);
      console.log(`  export E2E_TENANT_${label}_APPOINTMENT_ID=<uuid>`);
    }
    console.log('[seed-journey] dry-run OK');
    return;
  }

  const result = await seedJourneyFixtures();
  console.log('\n# Paste into your shell before running e2e:journeys (or rely on globalSetup auto-load):\n');
  for (const [k, v] of Object.entries(result.envVars)) {
    console.log(`export ${k}=${v}`);
  }
  console.log(`\n[seed-journey] wrote ${result.envFilePath}`);
}

const isMainModule =
  typeof require !== 'undefined' && typeof module !== 'undefined' && require.main === module;
if (isMainModule || import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error('[seed-journey] failed:', err);
    process.exit(1);
  });
}
