// @vitest-environment jsdom
import { cleanup, fireEvent, render, waitFor } from '@testing-library/react';
import { createElement } from 'react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { AgreementDetail } from '../api/agreements';

const h = vi.hoisted(() => ({
  push: vi.fn(),
  data: null as AgreementDetail | null,
  endpoint: null as string | null,
  permissions: [] as string[],
  refetch: vi.fn(),
  pauseAgreement: vi.fn(),
  resumeAgreement: vi.fn(),
  cancelAgreement: vi.fn(),
}));

vi.mock('expo-router', () => ({
  useLocalSearchParams: () => ({ id: 'agr-1' }),
  useRouter: () => ({ push: h.push, back: vi.fn(), replace: vi.fn() }),
}));
vi.mock('../hooks/useDetailQuery', () => ({
  useDetailQuery: (endpoint: string | null) => {
    h.endpoint = endpoint;
    return { data: h.data, isLoading: false, error: null, refetch: h.refetch };
  },
}));
vi.mock('../hooks/useMe', () => ({ useMe: () => ({ me: { permissions: h.permissions, timezone: 'UTC' } }) }));
vi.mock('../lib/useApiClient', () => {
  const client = vi.fn();
  return { useApiClient: () => client };
});
vi.mock('../api/agreements', () => ({
  pauseAgreement: (...a: unknown[]) => h.pauseAgreement(...a),
  resumeAgreement: (...a: unknown[]) => h.resumeAgreement(...a),
  cancelAgreement: (...a: unknown[]) => h.cancelAgreement(...a),
}));

// eslint-disable-next-line import/first
import AgreementDetailScreen from '../../app/agreements/[id]';

function agreement(overrides: Partial<AgreementDetail> = {}): AgreementDetail {
  return {
    id: 'agr-1',
    customerId: 'c1',
    name: 'Quarterly HVAC',
    recurrenceRule: 'FREQ=QUARTERLY',
    priceCents: 15000,
    autoGenerateInvoice: true,
    autoGenerateJob: false,
    nextRunAt: '2026-08-01T00:00:00Z',
    status: 'active',
    startsOn: '2026-01-01',
    recentRuns: [],
    ...overrides,
  };
}

const MANAGE = ['customers:update', 'customers:delete'];

beforeEach(() => {
  vi.clearAllMocks();
  h.data = null;
  h.endpoint = null;
  h.permissions = [...MANAGE];
  h.pauseAgreement.mockResolvedValue(undefined);
  h.resumeAgreement.mockResolvedValue(undefined);
  h.cancelAgreement.mockResolvedValue(undefined);
});

afterEach(() => cleanup());

describe('Agreement detail screen', () => {
  it('fetches by id and renders price + recurrence', () => {
    h.data = agreement();
    const { getByText, getAllByText } = render(createElement(AgreementDetailScreen));
    expect(h.endpoint).toBe('/api/agreements/agr-1');
    expect(getByText('$150.00', { exact: false })).toBeTruthy();
    // Recurrence appears in the headline (nested Text → parent + child both match).
    expect(getAllByText(/Quarterly/).length).toBeGreaterThan(0);
  });

  it('pauses an active agreement', async () => {
    h.data = agreement({ status: 'active' });
    const { getByText, queryByText } = render(createElement(AgreementDetailScreen));
    expect(queryByText('Resume')).toBeNull();
    fireEvent.click(getByText('Pause'));
    await waitFor(() => expect(h.pauseAgreement).toHaveBeenCalledWith(expect.anything(), 'agr-1'));
    expect(h.refetch).toHaveBeenCalled();
  });

  it('resumes a paused agreement', async () => {
    h.data = agreement({ status: 'paused' });
    const { getByText, queryByText } = render(createElement(AgreementDetailScreen));
    expect(queryByText('Pause')).toBeNull();
    fireEvent.click(getByText('Resume'));
    await waitFor(() => expect(h.resumeAgreement).toHaveBeenCalledWith(expect.anything(), 'agr-1'));
  });

  it('cancels behind a confirm step', async () => {
    h.data = agreement({ status: 'active' });
    const { getByText } = render(createElement(AgreementDetailScreen));
    fireEvent.click(getByText('Cancel agreement'));
    // Confirm dialog appears; the destructive confirm actually calls the API.
    fireEvent.click(getByText('Cancel it'));
    await waitFor(() => expect(h.cancelAgreement).toHaveBeenCalledWith(expect.anything(), 'agr-1'));
  });

  it('shows no actions for a cancelled agreement', () => {
    h.data = agreement({ status: 'cancelled' });
    const { getByText, queryByText } = render(createElement(AgreementDetailScreen));
    expect(getByText(/was cancelled/)).toBeTruthy();
    expect(queryByText('Pause')).toBeNull();
    expect(queryByText('Cancel agreement')).toBeNull();
  });

  it('gates pause on customers:update and cancel on customers:delete', () => {
    h.permissions = ['customers:view'];
    h.data = agreement({ status: 'active' });
    const { queryByText } = render(createElement(AgreementDetailScreen));
    expect(queryByText('Pause')).toBeNull();
    expect(queryByText('Cancel agreement')).toBeNull();
  });

  it('opens the invoice generated by a run', () => {
    h.data = agreement({
      recentRuns: [
        { id: 'run-1', scheduledFor: '2026-07-01', status: 'generated', generatedInvoiceId: 'inv-77' },
      ],
    });
    const { getByText } = render(createElement(AgreementDetailScreen));
    fireEvent.click(getByText('View invoice ›').closest('button')!);
    expect(h.push).toHaveBeenCalledWith('/invoices/inv-77');
  });
});
