/**
 * curated-seed.ts — HAND-AUTHORED utterance seed for the ServiceOS voice agent.
 *
 * This is the human-curated portion of the corpus. Every utterance here was
 * written/curated by the author of this pass to reflect how real trades
 * customers and operators actually speak (terse, rambling, regional, code-
 * switching), NOT an AI summary of what they "might" say. These rows are
 * emitted with source="curated", reviewed_by_human=true.
 *
 * `reviewed_by_human=true` here means: authored & curated by a human-in-the-loop
 * during this pass (see data/corpus/README.md for the precise semantics — it is
 * NOT a claim of independent third-party QA).
 *
 * A Seed is either a plain utterance string, or a [text, slots] tuple when the
 * utterance carries labeled slots used by the slot-extraction eval. Critical
 * slots: name, address, service_type, time_window, problem_description.
 */
export type Slots = Record<string, string>;
export type Seed = string | [string, Slots];

export const CURATED: Record<string, Seed[]> = {
  create_appointment: [
    ['Hi, I need to get someone out to look at my AC, it stopped cooling.', { service_type: 'hvac', problem_description: 'AC stopped cooling' }],
    ['Can I schedule a plumber for tomorrow morning? My kitchen sink is clogged.', { service_type: 'plumbing', time_window: 'tomorrow morning', problem_description: 'kitchen sink clogged' }],
    ['I\'d like to book a service call. This is Maria Lopez at 412 Elm Street.', { name: 'Maria Lopez', address: '412 Elm Street' }],
    ['We need an electrician out, some outlets stopped working. Whenever you can get here.', { service_type: 'electrical', problem_description: 'outlets stopped working' }],
    ['Could you send a tech out Thursday afternoon between 2 and 4?', { time_window: 'Thursday 2-4 PM' }],
    ['My furnace isn\'t kicking on and it\'s getting cold, can someone come today?', { service_type: 'hvac', problem_description: 'furnace not turning on', time_window: 'today' }],
    ['I want to set up an appointment for a water heater that\'s leaking.', { service_type: 'plumbing', problem_description: 'water heater leaking' }],
    ['Need to book a visit. Name\'s John Carter, 88 Maple Ave, the toilet keeps running.', { name: 'John Carter', address: '88 Maple Ave', problem_description: 'toilet keeps running' }],
    'Hey can y\'all come out and take a look at my heat pump sometime this week?',
    ['Schedule me for the earliest slot you got, the drain in the basement is backing up.', { problem_description: 'basement drain backing up', time_window: 'earliest available' }],
    ['Quiero agendar una cita para el aire acondicionado, no enfría.', { service_type: 'hvac', problem_description: 'AC not cooling' }],
    'I think I need to make an appointment for my garbage disposal, it\'s jammed.',
    ['Put me down for next Monday, address is 1500 Sunset Blvd, it\'s for an estimate on a new panel.', { time_window: 'next Monday', address: '1500 Sunset Blvd', service_type: 'electrical' }],
    'Can we get a guy out here? The whole upstairs is hot and the downstairs is fine.',
    ['Yeah I\'d like to schedule, my name is Dave, the breaker keeps tripping in the garage.', { name: 'Dave', service_type: 'electrical', problem_description: 'breaker keeps tripping' }],
    ['Book a plumber for Saturday if you\'re open, low water pressure all over the house.', { service_type: 'plumbing', time_window: 'Saturday', problem_description: 'low water pressure' }],
  ],
  draft_estimate: [
    ['How much would it cost to replace my water heater? Can you write up a quote?', { service_type: 'plumbing', problem_description: 'replace water heater' }],
    'Can you give me an estimate for a new AC unit?',
    ['I want a price on rewiring the kitchen, it\'s an old house with knob and tube.', { service_type: 'electrical', problem_description: 'rewire kitchen, knob and tube' }],
    'What would you charge to install a whole house generator?',
    ['Can I get a written estimate for a sewer line replacement at 22 Oak Court?', { service_type: 'plumbing', address: '22 Oak Court', problem_description: 'sewer line replacement' }],
    'Ballpark me — what\'s a mini split run cost these days?',
    ['Could you quote me on adding a 240 outlet for my EV charger?', { service_type: 'electrical', problem_description: 'add 240v outlet for EV charger' }],
    'I need an estimate for duct cleaning and a tune up.',
    ['Write me up an estimate for replacing the P-trap and the angle stops under the sink.', { service_type: 'plumbing', problem_description: 'replace P-trap and angle stops' }],
    '¿Cuánto me costaría un calentador de agua nuevo? Necesito una cotización.',
    'How much for a panel upgrade to 200 amp, roughly?',
    ['Give me a quote for a heat pump retrofit, we\'ve never had AC.', { service_type: 'hvac', problem_description: 'heat pump retrofit, no existing AC' }],
    'Can you price out fixing the slab leak? I heard water running under the floor.',
    'I\'d like an estimate before I commit to anything, just the diagnostic and a number.',
    'What\'s it gonna run me to swap out the furnace and the AC at the same time?',
  ],
  create_invoice: [
    'Can you put together an invoice for the job we finished at the Henderson place?',
    ['Bill the customer for the water heater install, parts and labor.', { service_type: 'plumbing' }],
    'I need to create an invoice for Mrs. Patterson, the AC repair from yesterday.',
    'Write up a bill for the service call, it was the diagnostic plus the capacitor.',
    'Go ahead and invoice them for the full amount we agreed on.',
    ['Make an invoice for 350 dollars for the drain cleaning.', { amount: '$350' }],
    'Set up the invoice for the panel upgrade we did over on Birch.',
    'Can you generate an invoice for the two-hour labor and the contactor?',
    'I want to bill out the furnace tune-up we just completed.',
    'Create a new invoice for the customer, same as the estimate I sent.',
    'Invoice the Thompson job — disposal replacement and the supply lines.',
    'Let\'s get an invoice out for the emergency call last night.',
    'Bill them for the trip charge and the part, that\'s it.',
    'I need an invoice drawn up for the mini split install.',
  ],
  update_invoice: [
    'Add a line item to that invoice for the extra refrigerant we used.',
    'Can you update the invoice and take off the trip charge?',
    'I need to add labor hours to the invoice for the Carter job.',
    'Change the invoice — they also approved the surge protector, add that.',
    'Update that bill, the part was more expensive than I quoted.',
    'Add the second visit to the existing invoice please.',
    'Take the disposal off the invoice, they decided not to do it.',
    'Edit the invoice to include the permit fee.',
    'Bump the labor to three hours on that invoice.',
    'Can you add the warranty line to the invoice for me?',
    'Update the invoice total, I gave them a fifty dollar discount.',
    'Add a line for the float switch on that AC invoice.',
  ],
  update_estimate: [
    'Update the estimate to include the duct sealing too.',
    'Can you revise the quote? They want the higher SEER unit now.',
    'Change the estimate, add a second condenser for the upstairs.',
    'Take the UV light off the estimate, they don\'t want it.',
    'Revise the estimate to 200 amp instead of 150.',
    'Add the expansion tank to the water heater estimate.',
    'Update the quote with the new refrigerant pricing.',
    'They want to add a whole house surge protector to the estimate.',
    'Can you edit the estimate to include the haul-away fee?',
    'Lower the estimate, I\'m gonna comp the diagnostic.',
    'Revise the quote to reflect the financing option.',
    'Add the second bathroom to that repipe estimate.',
  ],
  issue_invoice: [
    'Go ahead and finalize that invoice and send it to the customer.',
    'The invoice looks good, issue it.',
    'Send out the finished invoice for the Henderson job.',
    'Finalize invoice 1042 and email it to them.',
    'That bill is ready, go ahead and issue it.',
    'Push the invoice to the customer, it\'s approved.',
    'Issue the invoice for the AC repair, they\'re ready to pay.',
    'Finalize and send the invoice please.',
    'The invoice is correct now, release it to the customer.',
    'Send the final invoice to Mrs. Lopez.',
    'Go ahead and issue invoice number 88.',
    'That one\'s good, issue it and send the payment link.',
  ],
  create_customer: [
    ['Set up a new customer — name is Robert Klein, phone is 5551234567.', { name: 'Robert Klein', phone: '5551234567' }],
    ['Add a new customer, Sandra Diaz, she\'s at 90 Pine Street.', { name: 'Sandra Diaz', address: '90 Pine Street' }],
    'I\'ve got a new client, can you create their record?',
    ['New customer: Tom Bradley, email is tom@example.com.', { name: 'Tom Bradley', email: 'tom@example.com' }],
    'Create a customer profile for the lady who just called about the furnace.',
    ['Add this person — Jennifer Wu, 314 Birch Lane, cell 5559876543.', { name: 'Jennifer Wu', address: '314 Birch Lane', phone: '5559876543' }],
    'Set up a new account for the Hendersons.',
    'I need to add a new customer to the system before I book them.',
    ['Crear un cliente nuevo, se llama Carlos Mendez.', { name: 'Carlos Mendez' }],
    'Make a new customer record, they\'re a referral from the Smiths.',
    ['New client, Gary Olsen, address 7 Lakeview Drive.', { name: 'Gary Olsen', address: '7 Lakeview Drive' }],
    'Can you add a customer? First name Patricia, last name Hall.',
    'Create a new contact for the property manager at the apartments.',
  ],
  create_job: [
    ['Open a job for the AC replacement at 412 Elm Street.', { service_type: 'hvac', address: '412 Elm Street', problem_description: 'AC replacement' }],
    'Create a work order for the sewer repair we scoped today.',
    'Set up a new job for the panel upgrade on Birch.',
    ['Start a job for Mrs. Patterson, water heater install.', { name: 'Mrs. Patterson', problem_description: 'water heater install' }],
    'Open a work order for the duct replacement.',
    'I need a job created for the slab leak repair.',
    'Create the job for the mini split, two heads.',
    'Spin up a work order for the generator install at the Klein place.',
    'New job — repipe the whole house on Oak Court.',
    'Open a job ticket for the furnace they approved.',
    'Make a job for the drain line excavation.',
    'Create a work order for the EV charger install.',
  ],
  reschedule_appointment: [
    ['I need to move my appointment to Friday instead.', { time_window: 'Friday' }],
    'Can we push my service call back a day? Something came up.',
    ['Reschedule me for next week, Tuesday if you have it.', { time_window: 'next Tuesday' }],
    'I won\'t be home at 2, can we do later in the afternoon?',
    ['Move the Carter appointment to the morning slot.', { name: 'Carter', time_window: 'morning' }],
    'I gotta change my appointment, can you bump it to Monday?',
    'Something\'s come up, can we reschedule for the weekend?',
    'Push my furnace appointment to tomorrow please.',
    'Necesito cambiar mi cita para otro día.',
    'Can you reschedule the plumber for Wednesday instead of today?',
    ['Move my 10 AM to like 3 or 4 if that works.', { time_window: '3-4 PM' }],
    'I need to push back the install, the room isn\'t ready yet.',
  ],
  cancel_appointment: [
    'I need to cancel my appointment today.',
    'Go ahead and cancel the service call, we fixed it ourselves.',
    'Cancel my plumber for tomorrow, I\'ll call back later.',
    'I want to cancel the appointment, we\'re going with someone else.',
    ['Cancel the Henderson appointment please.', { name: 'Henderson' }],
    'Scratch my appointment for Friday.',
    'We don\'t need the tech anymore, cancel it.',
    'Please cancel — turns out it was just the breaker.',
    'Cancelar mi cita por favor.',
    'Cancel the AC tune up, I\'m out of town.',
    'Take me off the schedule for Thursday.',
    'I have to cancel, can you remove my appointment?',
  ],
  reassign_appointment: [
    ['Reassign the 2 o\'clock job to Mike.', { technician: 'Mike', time_window: '2 PM' }],
    'Move the Birch Street call to a different tech, Carlos is out sick.',
    'Can you put Dave on the Henderson appointment instead?',
    'Reassign the afternoon route to Tony.',
    'Switch the technician on that job, Mike\'s overbooked.',
    'Give the emergency call to whoever\'s closest.',
    'Reassign the panel job to the senior electrician.',
    'Put a different guy on the 9 AM, Carlos has a flat.',
    'Move that install over to the other crew.',
    'Assign the Oak Court job to Jennifer.',
    'Hand the furnace call off to Tony, he\'s nearby.',
    'Reassign the rest of my route, I\'m stuck on this one.',
  ],
  add_note: [
    'Add a note that the gate code is 1234.',
    ['Put a note on the Carter account — dog in the backyard.', { name: 'Carter' }],
    'Note that the customer prefers afternoon appointments.',
    'Add to the job notes: the access panel is behind the dryer.',
    'Make a note the customer is hard of hearing, knock loud.',
    'Note on the file — they want a call 30 minutes out.',
    'Add a note that parking is in the rear.',
    'Put in the notes that the old unit is a 1998 Trane.',
    'Note that they already have the part, just need install.',
    'Add a note: customer mentioned a warranty, check it.',
    'Jot down that the basement floods when it rains.',
    'Note for the tech — bring a ladder, it\'s a high ceiling.',
  ],
  send_invoice: [
    'Text the invoice to the customer please.',
    'Email that invoice over to Mrs. Lopez.',
    ['Send the invoice to the Henderson job by text.', { name: 'Henderson', channel: 'sms' }],
    'Can you resend the invoice? They didn\'t get it.',
    'Send the bill to their email on file.',
    'Shoot the invoice over to the customer.',
    'Forward the invoice to the property manager.',
    'Send invoice 1042 to the customer by email.',
    'Text them the payment link and the invoice.',
    'Re-send the invoice to the new number.',
    'Send the invoice to both the husband and wife.',
    'Push the invoice out by SMS please.',
  ],
  send_estimate: [
    'Email the estimate to the customer.',
    'Text the quote over to them please.',
    ['Send the estimate for the AC to Mr. Bradley.', { name: 'Mr. Bradley', service_type: 'hvac', channel: 'email' }],
    'Can you send them the written estimate?',
    'Forward the quote to their email.',
    'Send the estimate so they can review it tonight.',
    'Resend the estimate, they lost the first one.',
    'Text the customer the estimate link.',
    'Send the quote to the wife\'s number too.',
    'Email the estimate and the financing options.',
    'Get that estimate out to the customer today.',
    'Send the proposal over to the Kleins.',
  ],
  record_payment: [
    ['Record a payment of 350 dollars on the Carter invoice.', { amount: '$350', name: 'Carter' }],
    'The customer paid cash, mark it paid.',
    ['Log a card payment for the AC repair, 480 bucks.', { amount: '$480', payment_method: 'card' }],
    'They paid by check, record it.',
    'Mark invoice 88 as paid in full.',
    'Take a payment of 200 toward their balance.',
    'Customer paid half today, record 250.',
    'Record the deposit, they put down 500.',
    'Apply a payment to the Henderson account.',
    'They Venmo\'d me, log it as paid.',
    'Mark the estimate deposit as received.',
    'Record full payment on the water heater job.',
  ],
  emergency_dispatch: [
    ['I smell gas in my house, I need someone right now!', { problem_description: 'gas smell', service_type: 'plumbing' }],
    ['There\'s water pouring out of the ceiling, please hurry!', { problem_description: 'water pouring from ceiling', service_type: 'plumbing' }],
    ['My basement is flooding, the pipe burst!', { problem_description: 'burst pipe, basement flooding', service_type: 'plumbing' }],
    ['No heat and it\'s below freezing, I have a baby in the house.', { problem_description: 'no heat in freezing weather', service_type: 'hvac', time_window: 'now' }],
    ['I think there\'s an electrical fire, the outlet is sparking and smoking!', { problem_description: 'outlet sparking and smoking', service_type: 'electrical' }],
    ['Sewage is backing up into the tub, it\'s an emergency.', { problem_description: 'sewage backup into tub', service_type: 'plumbing' }],
    ['Carbon monoxide detector is going off, what do I do?', { problem_description: 'CO detector alarm' }],
    ['Water heater is spraying everywhere, I can\'t find the shutoff!', { problem_description: 'water heater spraying', service_type: 'plumbing' }],
    ['The whole house lost power and I smell something burning at the panel.', { problem_description: 'power out, burning smell at panel', service_type: 'electrical' }],
    ['Hay olor a gas en la casa, necesito ayuda urgente.', { problem_description: 'gas smell', service_type: 'plumbing' }],
    'It\'s 105 out and my AC died, my mom is elderly and it\'s dangerous in here.',
    'There\'s a burning smell coming from the furnace and smoke, send someone now.',
  ],
  update_customer: [
    ['Update the phone number on the Carter account to 5550001111.', { name: 'Carter', phone: '5550001111' }],
    'Change the customer\'s address, they moved.',
    'Update the email on file for Mrs. Lopez.',
    'Fix the spelling of the customer\'s name, it\'s Klein with a K.',
    ['Add a second phone number for the customer.', {}],
    'Update their billing address, it\'s different from the service address.',
    'Change the primary contact to the husband.',
    'Update the gate code on the customer record.',
    'The customer got a new number, update it.',
    'Correct the address — it\'s Pine Street not Pine Avenue.',
    'Update the customer\'s preferred contact to text.',
    'Change the name on the account, she got married.',
  ],
  log_expense: [
    ['Log an expense, 85 dollars for the capacitor at the supply house.', { amount: '$85', expense_category: 'parts' }],
    'Add a material expense for the copper I bought.',
    'I spent 200 on parts for the Henderson job, log it.',
    'Record a fuel expense for today.',
    'Log the permit fee as a job expense.',
    'Add the disposal fee to the job costs.',
    'I picked up a water heater, log the expense to the job.',
    'Record 40 bucks for the refrigerant.',
    'Log my parking and tolls for the downtown job.',
    'Add an expense for the rental equipment.',
    'Put the supply house receipt against the Oak Court job.',
    'Log a materials cost of 150 for the panel.',
  ],
  convert_lead: [
    'Turn that lead into a customer, they want to book.',
    'Convert the lead from the website, they\'re ready.',
    'The estimate lead said yes, make them a customer.',
    'Convert Mr. Bradley from a lead to a job.',
    'That referral is ready to go, convert the lead.',
    'Move the lead to a customer and book the install.',
    'Convert the lead and create the job for the AC.',
    'They approved the quote, convert the lead.',
    'Turn the Facebook lead into a real customer.',
    'Convert the lead, they paid the deposit.',
    'Make that prospect a customer, they\'re a go.',
    'Convert the lead from yesterday\'s open house.',
  ],
  confirm_appointment: [
    'Just calling to confirm my appointment for tomorrow.',
    'Is my service call still on for Thursday?',
    'I wanted to make sure the tech is still coming today.',
    'Confirming the 2 to 4 window for my AC.',
    'Can you confirm my appointment is booked?',
    'Just double checking someone\'s coming Friday morning.',
    'Confirm the install is still scheduled for Monday.',
    'I got a reminder, yes I\'ll be home, confirm it.',
    'Wanted to verify my plumber appointment.',
    'Still good for tomorrow at 10?',
    'Confirming you\'ll be out for the water heater.',
    'Yes please confirm, I\'ll be there.',
  ],
  mark_lead_lost: [
    'Mark that lead as lost, they went with a competitor.',
    'The Bradley lead is dead, close it out.',
    'They never called back, mark the lead lost.',
    'Lost that one on price, mark it lost.',
    'Close the lead, they decided not to do it.',
    'Mark the website lead as lost, no response.',
    'That prospect ghosted us, mark it lost.',
    'They went with their cousin, lost lead.',
    'Mark the lead dead, out of our service area.',
    'Close out the lead, it was a tire kicker.',
    'Lost — they didn\'t like the estimate, mark it.',
    'Set that lead to lost, too far out.',
  ],
  add_service_location: [
    ['Add a second address for this customer, 200 Market Street.', { address: '200 Market Street' }],
    'They have a rental property too, add that address.',
    'Add another service location for the Kleins.',
    'The customer owns a duplex, add the second unit.',
    'Add their business address as a service location.',
    'They bought a new house, add it to their account.',
    'Add the vacation home as another location.',
    'Customer has two properties, add the second one.',
    'Add a service address for the mother-in-law\'s place.',
    'They manage three buildings, add all the addresses.',
    'Add the shop address as a service location.',
    'New address for the same customer, add it please.',
  ],
  log_time_entry: [
    ['Log two hours of labor on the Henderson job.', { duration: '2 hours' }],
    'Clock me in three hours for the panel upgrade.',
    'Add my time to the job, started at 8 ended at noon.',
    'Log an hour and a half for the diagnostic.',
    'Put four hours of labor on the repipe.',
    'Record my time on the AC install, full day.',
    'Log 45 minutes for the service call.',
    'Add labor time, two techs two hours each.',
    'Clock the apprentice in for the duct job.',
    'Log my drive time and the two hours on site.',
    'Record six hours on the generator install.',
    'Add my hours for the Oak Court job.',
  ],
  notify_delay: [
    'Let the customer know I\'m running about 30 minutes late.',
    'Text the Carter job that I\'m delayed on the previous call.',
    'Tell them I\'ll be there closer to 3 instead of 2.',
    'Let the next customer know I\'m behind schedule.',
    'Notify the Henderson appointment I\'m running late.',
    'Message them, traffic is bad, I\'ll be 20 minutes.',
    'Tell the customer the prior job ran long.',
    'Let them know I\'m on my way but delayed.',
    'Notify my 4 o\'clock I might be a little late.',
    'Text them I\'m pushing back an hour.',
    'Let the customer know the part run delayed me.',
    'Tell them I\'ll call when I\'m 15 out, running behind.',
  ],
  request_feedback: [
    'Send the customer a review request after the job.',
    'Ask Mrs. Lopez for a Google review.',
    'Text the customer the feedback link.',
    'Request a review from the Henderson job.',
    'Send a follow up asking how we did.',
    'Ask them to leave us a review please.',
    'Send the survey to the customer.',
    'Request feedback on the AC install.',
    'Send a review ask to the last three customers.',
    'Text them and ask for a star rating.',
    'Follow up with the customer for a testimonial.',
    'Send the review request to the Kleins.',
  ],
  lookup_appointments: [
    ['What appointments do I have tomorrow?', { time_window: 'tomorrow' }],
    'Pull up my schedule for today.',
    'When is my next service call?',
    ['Show me the Henderson appointments.', { name: 'Henderson' }],
    'What\'s on the calendar for Friday?',
    'Do I have anything booked this afternoon?',
    'List my appointments for next week.',
    'When\'s the AC install scheduled?',
    'Check if the customer has an upcoming appointment.',
    'What time is my first job tomorrow?',
    'Show me all the appointments on Oak Court.',
    'How many calls do I have left today?',
  ],
  lookup_invoices: [
    ['Pull up the invoices for the Carter account.', { name: 'Carter' }],
    'What invoices are outstanding?',
    'Show me the customer\'s invoice history.',
    'Find invoice 1042 for me.',
    'List all unpaid invoices.',
    'What did we bill the Hendersons?',
    'Pull the invoice for the water heater job.',
    'Show invoices from last month.',
    'Did we ever invoice the Oak Court job?',
    'Find the invoice for Mrs. Lopez.',
    'What\'s the total on the customer\'s last invoice?',
    'Show me all invoices for this customer.',
  ],
  lookup_balance: [
    ['What\'s the balance on the Carter account?', { name: 'Carter' }],
    'How much does this customer owe?',
    'Check the outstanding balance for Mrs. Lopez.',
    'What do I owe you guys?',
    'Pull up my account balance.',
    'How much is left on the invoice?',
    'What\'s my current balance?',
    'Does the customer have any open balance?',
    'How much is the Henderson account behind?',
    'Tell me the balance due on the job.',
    'What\'s the remaining balance after the deposit?',
    'Check if this customer owes anything.',
  ],
  lookup_jobs: [
    ['Show me the open jobs.', {}],
    'What jobs are scheduled this week?',
    'Pull up the Henderson work order.',
    'List all the active jobs.',
    'What\'s the status of the repipe job?',
    'Find the job for the panel upgrade.',
    'Show me jobs that are waiting on parts.',
    'How many jobs do we have open?',
    'Pull the work order for Oak Court.',
    'What jobs did we complete today?',
    'Show the job history for this customer.',
    'Find the AC replacement job.',
  ],
  lookup_agreements: [
    ['Does this customer have a service agreement?', {}],
    'Pull up the maintenance contract for the Hendersons.',
    'What agreements are expiring this month?',
    'Check if Mrs. Lopez has a membership.',
    'Show me the service plan details.',
    'Is the customer on a maintenance plan?',
    'List all active service agreements.',
    'When does the Carter agreement renew?',
    'Pull the contract for the Oak Court property.',
    'Does this account have a warranty agreement?',
    'Show me the membership status.',
    'What\'s covered under their service plan?',
  ],
  lookup_account_summary: [
    ['Give me a summary of the Carter account.', { name: 'Carter' }],
    'Pull up everything on this customer.',
    'What\'s the overview for the Henderson account?',
    'Summarize this customer\'s history.',
    'Give me the rundown on Mrs. Lopez.',
    'Show me the account summary.',
    'What\'s the full picture on this account?',
    'Pull the customer overview.',
    'Give me the highlights on the Oak Court account.',
    'Summarize what we\'ve done for this customer.',
    'What\'s the account status overall?',
    'Show me the customer snapshot.',
  ],
  lookup_customer: [
    ['Look up the customer at 412 Elm Street.', { address: '412 Elm Street' }],
    ['Find the record for John Carter.', { name: 'John Carter' }],
    'Search for the customer by phone number.',
    'Pull up Mrs. Lopez\'s file.',
    'Do we have this person in the system?',
    'Find the customer with the Birch Street address.',
    'Look up the Henderson account.',
    'Search for a customer named Sandra.',
    'Is this caller already a customer?',
    'Find the record by the phone number on the caller ID.',
    'Pull up the customer profile for the Kleins.',
    'Look up who\'s at 88 Maple Ave.',
  ],
  lookup_estimates: [
    ['Pull up the estimates for the Bradley account.', { name: 'Bradley' }],
    'What estimates are still pending?',
    'Find the quote we sent for the AC.',
    'Show me the customer\'s estimate history.',
    'Did we send an estimate to the Hendersons?',
    'List all open estimates.',
    'Pull the estimate for the panel upgrade.',
    'What\'s the status of the water heater quote?',
    'Show estimates from this week.',
    'Find the estimate for Oak Court.',
    'What did we quote the customer?',
    'Show me all pending estimates over 5 grand.',
  ],
  lookup_availability: [
    ['What\'s my availability tomorrow afternoon?', { time_window: 'tomorrow afternoon' }],
    'When\'s the next open slot?',
    'Do we have any openings Friday?',
    ['When can a tech come out for an AC repair?', { service_type: 'hvac' }],
    'What times are open next week?',
    'Is there a same day slot available?',
    'When\'s the earliest you could fit me in?',
    'Check the schedule for an opening Monday morning.',
    'Do you have anything this weekend?',
    'What\'s the first available for a plumber?',
    'When could someone come for an estimate?',
    'Are there any afternoon slots left today?',
  ],
  lookup_leads: [
    ['Show me the new leads.', {}],
    'How many leads came in this week?',
    'Pull up the leads from the website.',
    'What leads haven\'t been contacted yet?',
    'List the open leads.',
    'Show me leads from the Facebook campaign.',
    'How many leads are in the pipeline?',
    'Pull the lead for Mr. Bradley.',
    'What leads are we waiting to hear back from?',
    'Show me today\'s leads.',
    'List leads that need a follow up.',
    'How many leads converted this month?',
  ],
  lookup_revenue: [
    ['What\'s our revenue this month?', { time_window: 'this month' }],
    'How much did we bring in today?',
    'Pull up the revenue for last week.',
    'What were total sales for the quarter?',
    'How are we doing on revenue this year?',
    'Show me the income for September.',
    'What\'s the average ticket this month?',
    'How much revenue from HVAC versus plumbing?',
    'What did we collect this week?',
    'Show me the daily revenue numbers.',
    'How much have we billed this month?',
    'What\'s the revenue trend this quarter?',
  ],
  lookup_catalog: [
    ['What\'s the price on a standard water heater install?', { service_type: 'plumbing' }],
    'Pull up the price book for AC units.',
    'What do we charge for a drain cleaning?',
    'Show me the service catalog.',
    'What\'s the rate for a diagnostic?',
    'Look up the price for a panel upgrade.',
    'What services do we offer for electrical?',
    'Pull the flat rate for a capacitor replacement.',
    'What\'s in the catalog for maintenance plans?',
    'Show me the pricing for mini splits.',
    'What do we list for a sewer camera inspection?',
    'Look up the standard trip charge.',
  ],
  language_switch: [
    'Can we do this in Spanish?',
    '¿Podemos hablar en español?',
    'English please.',
    'Habla español?',
    'Switch to Spanish please.',
    'I\'d prefer English if that\'s okay.',
    '¿Hay alguien que hable español?',
    'Can I get someone who speaks Spanish?',
    'Let\'s switch to English.',
    'Prefiero español, por favor.',
    'Do you have a Spanish speaker?',
    'Can you talk to me in English instead?',
  ],
  operator_request: [
    'Can I talk to a real person?',
    'I want to speak with a human.',
    'Get me a live agent please.',
    'Can you transfer me to someone?',
    'I\'d rather talk to a person.',
    'Put me through to a representative.',
    'Is there someone I can actually talk to?',
    'I need to speak with the owner.',
    'Stop, I want a human.',
    'Transfer me to the office.',
    'Can I just talk to one of your people?',
    'Let me speak to a dispatcher.',
  ],
  confirm: [
    'Yes, that\'s right.',
    'Yep, go ahead.',
    'That works for me.',
    'Correct.',
    'Sounds good.',
    'Yes please.',
    'That\'s correct, do it.',
    'Okay, yeah, book it.',
    'Perfect, that\'s fine.',
    'Sí, está bien.',
    'Yeah that\'s what I want.',
    'Go for it.',
  ],
  unknown: [
    'How\'s the weather over there?',
    'Do you guys sell cars?',
    'Is this the pizza place?',
    'I\'m just doing a survey, do you have a minute?',
    'What\'s your favorite color?',
    'Can you help me with my taxes?',
    'I think I dialed the wrong number.',
    'Do you know what time the bank closes?',
    'Are you hiring?',
    'Just testing my phone, ignore me.',
    'Can you recommend a good restaurant?',
    'Wrong number, sorry.',
  ],
};
