/**
 * Generates src/ai/untrusted-confusables.generated.ts — the confusable fold
 * the untrusted-text matching copy uses (#1229 security re-review: hand
 * confusable lists missed Lisu and stroke letters).
 *
 * Inputs (Unicode data files, not vendored — download the version you pin):
 *   --confusables   https://www.unicode.org/Public/security/<ver>/confusables.txt
 *   --unicode-data  https://www.unicode.org/Public/<ver>/ucd/UnicodeData.txt
 *
 * Usage:
 *   npx tsx scripts/generate-untrusted-confusables.ts \
 *     --confusables /tmp/confusables.txt --unicode-data /tmp/UnicodeData.txt
 *
 * What is kept, so the table stays small:
 *   - UTS #39 single-code-point sources outside ASCII (ASCII letters and
 *     digits are never remapped) whose prototype, with combining marks
 *     removed, is ASCII letters/digits (`ꓴ`→U, `Ŧ`→T from `T̵`) or one of
 *     the delimiters the matchers look for (`<>[]/=()-`);
 *   - keyed by the source's own fold (NFKC, NFD, marks dropped) — the form
 *     the runtime looks up — and only when that fold does not already equal
 *     the target (NFKC covers fullwidth, mathematical and enclosed forms);
 *   - plus `LATIN LETTER SMALL CAPITAL X` → X from UnicodeData.txt names:
 *     UTS #39 does not list most small capitals, and they read as Latin.
 */
import * as fs from 'fs';
import * as path from 'path';

function arg(name: string): string {
  const i = process.argv.indexOf(`--${name}`);
  if (i < 0 || !process.argv[i + 1]) throw new Error(`missing --${name} <path>`);
  return process.argv[i + 1];
}

const confusablesPath = arg('confusables');
const unicodeDataPath = arg('unicode-data');
const OUT = path.resolve(__dirname, '../src/ai/untrusted-confusables.generated.ts');

function fold(s: string): string {
  return [...s.normalize('NFKC').normalize('NFD')].filter((c) => !/\p{M}/u.test(c)).join('');
}

const confusables = fs.readFileSync(confusablesPath, 'utf8');
const version = /^# Version: (\S+)/m.exec(confusables)?.[1];
const date = /^# Date: ([0-9-]+)/m.exec(confusables)?.[1];
if (!version || !date) throw new Error('confusables.txt header has no Version/Date');

const alnum = new Map<string, string>();
const delimiters = new Map<string, string>();
for (const raw of confusables.split('\n')) {
  const line = raw.replace(/^﻿/, '').split('#')[0].trim();
  if (!line) continue;
  const [src, tgt] = line.split(';').map((f) => f.trim());
  const srcCps = src.split(/\s+/);
  if (srcCps.length !== 1) continue;
  const source = String.fromCodePoint(parseInt(srcCps[0], 16));
  if (source.codePointAt(0)! <= 0x7f) continue;
  const target = fold(tgt.split(/\s+/).map((h) => String.fromCodePoint(parseInt(h, 16))).join(''));
  const key = fold(source);
  if ([...key].length !== 1 || key.codePointAt(0)! <= 0x7f) continue;
  if (key.toUpperCase() === target.toUpperCase()) continue;
  if (/^[A-Za-z0-9]+$/.test(target)) {
    if (!alnum.has(key)) alnum.set(key, target);
  } else if (/^[<>[\]/=()-]$/.test(target)) {
    if (!delimiters.has(key)) delimiters.set(key, target);
  }
}

const unicodeData = fs.readFileSync(unicodeDataPath, 'utf8');
let smallCapitals = 0;
for (const line of unicodeData.split('\n')) {
  const [cp, name] = line.split(';');
  const m = /^LATIN LETTER SMALL CAPITAL ([A-Z])$/.exec(name ?? '');
  if (!m) continue;
  const key = fold(String.fromCodePoint(parseInt(cp, 16)));
  if ([...key].length !== 1 || alnum.has(key)) continue;
  alnum.set(key, m[1]);
  smallCapitals++;
}

function escape(ch: string): string {
  return `\\u{${ch.codePointAt(0)!.toString(16).toUpperCase()}}`;
}

/** Entries as `<source><target>` joined by spaces, wrapped for review. */
function packed(map: Map<string, string>): string {
  const entries = [...map.entries()]
    .sort(([a], [b]) => a.codePointAt(0)! - b.codePointAt(0)!)
    .map(([k, v]) => `${escape(k)}${v}`);
  const lines: string[] = [];
  let current = '';
  for (const e of entries) {
    if (current.length + e.length + 1 > 96) {
      lines.push(current);
      current = '';
    }
    current += `${e} `;
  }
  if (current) lines.push(current);
  return lines.map((l) => `  '${l}'`).join(' +\n');
}

const source = `Unicode UTS #39 confusables.txt ${version} (${date}); UnicodeData.txt small-capital names`;
const out = `/**
 * GENERATED by scripts/generate-untrusted-confusables.ts — do not edit by hand.
 *
 * Source: ${source}.
 * ${alnum.size} letter/digit entries (${smallCapitals} small capitals from UnicodeData names), ${delimiters.size} delimiter entries.
 *
 * Each entry is a folded non-ASCII code point (NFKC, NFD, combining marks
 * dropped) followed by the ASCII it is confusable with; entries are separated
 * by one space. Parsed by untrusted-text-matching.ts.
 */

export const CONFUSABLES_SOURCE = '${source}';

/** Non-ASCII code point → ASCII letters/digits (UTS #39 prototype, marks removed). */
export const LETTER_CONFUSABLE_ENTRIES =
${packed(alnum)};

/** Non-ASCII code point → one of \`<>[]/=()-\` (UTS #39 prototype). */
export const DELIMITER_CONFUSABLE_ENTRIES =
${packed(delimiters)};
`;
fs.writeFileSync(OUT, out);
console.log(`wrote ${path.relative(process.cwd(), OUT)}: ${alnum.size} letter/digit, ${delimiters.size} delimiter entries (UTS #39 ${version})`);
