/**
 * P7-026 — Content-level PII redactor for public review responses.
 *
 * This is a DIFFERENT redactor from `packages/api/src/logging/redact.ts`:
 *   - That one is a key-pattern infra redactor (sanitises log objects
 *     by inspecting property names like "email", "phone").
 *   - This one is a content-level value redactor (sanitises a string
 *     of TEXT by spotting embedded PII tokens — phone numbers, email
 *     addresses, street addresses, last names, etc.).
 *
 * Why a separate redactor is mandatory (per the dispatch addendum's
 * highest-risk note — "PII leakage in public responses"):
 *   - The public draft is shown on a publicly-indexed Google review
 *     page. If the LLM-generated draft accidentally quotes the
 *     customer's address or phone number — even because the operator
 *     told it to "be more personal" — that PII is now searchable
 *     forever.
 *   - The infra redactor wouldn't catch this: it walks objects by
 *     KEY name and a generated paragraph of text has no keys.
 *
 * This redactor runs as the LAST PASS over every public draft before
 * the draft is attached to a proposal. It MUST be deterministic and
 * MUST NOT consult an LLM — a hostile prompt could otherwise convince
 * the LLM to "redact only the irrelevant PII" and let real PII through.
 *
 * Out-of-scope (intentionally):
 *   - First-name-only references are allowed ("Hi Susan, I'm sorry…")
 *     because they're not a unique identifier on a public page.
 *   - The reviewer's *own* name on the public page is already public —
 *     we don't redact it from the draft because Google itself shows it.
 *     Last names of OTHER people (e.g., a tech named Carlos Donovan)
 *     are stripped because the operator might paste internal data.
 */

export interface RedactionResult {
  redacted: string;
  redactions: Array<{ type: PiiType; original: string }>;
}

export type PiiType =
  | 'email'
  | 'phone'
  | 'street_address'
  | 'last_name'
  | 'ssn'
  | 'credit_card'
  | 'internal_id';

const EMAIL_RE = /\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\b/gi;

// North-American style phone numbers. Catches:
//   (415) 555-1234, 415-555-1234, 415.555.1234, +1 415 555 1234,
//   4155551234. NOT a strict E.164 parser — generous on purpose since
//   the cost of a false positive (one extra [REDACTED]) is low and
//   the cost of a false negative (a real phone leaked) is high.
const PHONE_RE = /(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\b/g;

// Street-address heuristic: number + 1-4 capitalized words + a street
// suffix. Deliberately broad to catch common variants.
const STREET_RE = new RegExp(
  `\\b\\d{1,6}\\s+(?:[A-Z][a-zA-Z]*\\s+){0,4}(?:Street|St|Avenue|Ave|Boulevard|Blvd|Road|Rd|Drive|Dr|Lane|Ln|Court|Ct|Way|Place|Pl|Highway|Hwy|Parkway|Pkwy|Circle|Cir|Terrace|Ter|Square|Sq)\\.?\\b`,
  'g',
);

const SSN_RE = /\b\d{3}-\d{2}-\d{4}\b/g;
const CREDIT_CARD_RE = /\b(?:\d{4}[\s-]?){3}\d{4}\b/g;
// Internal IDs match `<PREFIX>-<TOKEN>(-<TOKEN>)*` where each token is
// 3+ alphanumeric chars. Catches `JOB-001-ABCD`, `CUST-AB12CD`,
// `INV-2024-0042`, etc. The minimum-3 token length plus the `\b`
// boundary keeps false positives down.
const INTERNAL_ID_RE = /\b(?:CUST|JOB|INV|APPT|EST)-[A-Z0-9]{3,}(?:-[A-Z0-9]{3,})*\b/gi;

const REDACTED_TOKEN = '[redacted]';

export interface RedactPublicDraftInput {
  /** The draft text generated by the LLM (or a stub). */
  text: string;
  /**
   * Last names that the LLM might have been tempted to include — the
   * matched-customer's last name plus any technician names from the
   * tenant's team. The redactor strips these even if they appear
   * "naturally" because the rule is: no last names in public replies.
   */
  disallowedLastNames?: readonly string[];
}

export function redactPublicDraft(input: RedactPublicDraftInput): RedactionResult {
  let working = input.text;
  const redactions: RedactionResult['redactions'] = [];

  const collect = (re: RegExp, type: PiiType): void => {
    working = working.replace(re, (match) => {
      redactions.push({ type, original: match });
      return REDACTED_TOKEN;
    });
  };

  // Order matters: SSN and credit-card patterns first so a "555-12-3456"
  // isn't first eaten by the phone regex.
  collect(SSN_RE, 'ssn');
  collect(CREDIT_CARD_RE, 'credit_card');
  collect(EMAIL_RE, 'email');
  collect(PHONE_RE, 'phone');
  collect(STREET_RE, 'street_address');
  collect(INTERNAL_ID_RE, 'internal_id');

  // Disallowed last names — exact, case-insensitive, word-bounded.
  for (const lastName of input.disallowedLastNames ?? []) {
    const trimmed = lastName.trim();
    if (!trimmed) continue;
    const re = new RegExp(`\\b${escapeRegExp(trimmed)}\\b`, 'gi');
    working = working.replace(re, () => {
      redactions.push({ type: 'last_name', original: trimmed });
      return REDACTED_TOKEN;
    });
  }

  return { redacted: working, redactions };
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Strict variant: throws if the redactor found anything. Used by the
 * proposal-builder as a final assertion — even if a regex misfires
 * upstream, the proposal MUST NOT carry a public draft that the
 * redactor would flag. A throw here surfaces the regression instead
 * of silently shipping a leaked draft.
 */
export function assertNoPiiInPublicDraft(input: RedactPublicDraftInput): string {
  const { redacted, redactions } = redactPublicDraft(input);
  if (redactions.length > 0) {
    const types = Array.from(new Set(redactions.map((r) => r.type))).join(',');
    throw new Error(
      `Public draft failed PII redaction (types: ${types}). ` +
        `Surfaced ${redactions.length} potential leak(s).`,
    );
  }
  return redacted;
}
