#!/usr/bin/env bash
# qa-env — shared env loader for QA harness shell scripts.
#
# Sources (in order):
#   1. .env.qa        — operator secrets (gitignored)
#   2. .env.qa.local  — generated tenant IDs from npm run qa:setup (gitignored)
#
# Usage (from other scripts):
#   # shellcheck disable=SC1091
#   source "$(dirname "${BASH_SOURCE[0]}")/qa-env.sh"
#   load_qa_env
#   apply_qa_defaults
#   require_qa_env E2E_DB_URL_READWRITE

# Repo root: caller must cd to repo root before load, or set QA_REPO_ROOT.
_qa_repo_root() {
  if [ -n "${QA_REPO_ROOT:-}" ]; then
    echo "$QA_REPO_ROOT"
    return
  fi
  echo "$(cd "$(dirname "${BASH_SOURCE[1]:-${BASH_SOURCE[0]}}")/.." && pwd)"
}

load_qa_env() {
  local root
  root="$(_qa_repo_root)"
  if [ -f "$root/.env.qa" ]; then
    echo "Sourcing .env.qa"
    set -a
    # shellcheck disable=SC1091
    . "$root/.env.qa"
    set +a
  else
    echo "WARNING: $root/.env.qa not found — using env vars already in your shell." >&2
    echo "         Create it: cp .env.qa.example .env.qa && fill Railway secrets" >&2
  fi
  if [ -f "$root/.env.qa.local" ]; then
    echo "Sourcing .env.qa.local (generated tenant IDs)"
    set -a
    # shellcheck disable=SC1091
    . "$root/.env.qa.local"
    set +a
  fi
}

# Apply defaults when a var is unset OR empty (export VAR="" in .env.qa blocks :- otherwise).
apply_qa_defaults() {
  if [ -z "${E2E_BASE_URL:-}" ]; then
    export E2E_BASE_URL="https://serviceosweb-development.up.railway.app"
  fi
  if [ -z "${E2E_API_URL:-}" ]; then
    export E2E_API_URL="https://serviceosapi-development.up.railway.app"
  fi
  if [ -z "${E2E_DB_URL_READONLY:-}" ] && [ -n "${E2E_DB_URL_READWRITE:-}" ]; then
    export E2E_DB_URL_READONLY="$E2E_DB_URL_READWRITE"
  fi
  export BASE_URL="${BASE_URL:-$E2E_BASE_URL}"
  export API_URL="${API_URL:-$E2E_API_URL}"
}

require_qa_env() {
  local name="$1"
  local val="${!name:-}"
  if [ -n "$val" ]; then
    return 0
  fi
  echo "ERROR: required env var '$name' is empty or not set." >&2
  echo "       Edit .env.qa and paste the Railway value." >&2
  echo "       Template: .env.qa.example" >&2
  echo "       Guide:    docs/runbooks/qa-full-matrix-unblock.md" >&2
  case "$name" in
    E2E_DB_URL_READWRITE)
      echo "       Source: Railway → Postgres → Variables → DATABASE_PUBLIC_URL" >&2
      ;;
    E2E_DB_URL_READONLY)
      echo "       Source: qa_readonly role URL, or leave unset to mirror READWRITE" >&2
      ;;
    E2E_CLERK_HMAC_SECRET)
      echo "       Source: Railway → API service → Variables → CLERK_SECRET_KEY (value)" >&2
      ;;
    E2E_BASE_URL|E2E_API_URL)
      echo "       Source: Railway → service → Settings → Networking (*.up.railway.app)" >&2
      echo "       Or omit from .env.qa to use Railway dev defaults." >&2
      ;;
  esac
  exit 1
}

# Persist matrix tenant exports after qa:setup (idempotent re-runs overwrite).
write_qa_local_env() {
  local root line
  root="$(_qa_repo_root)"
  {
    echo "# Generated by npm run qa:setup — do not commit"
    echo "# Re-run qa:setup after DB re-seed to refresh tenant UUIDs"
    for line in "$@"; do
      echo "$line"
    done
  } >"$root/.env.qa.local"
  echo "Wrote $root/.env.qa.local (matrix tenant IDs for qa:matrix:run)"
}
