import re,sys
p='docs/PRD-v5-as-built.md'; s=open(p,encoding='utf-8').read()
CMD='`CLERK_DEV_HMAC_TOKENS=true DB_SSL=false DATABASE_URL=<testcontainer> E2E_USE_TEST_DB=true VITE_CLERK_PUBLISHABLE_KEY=pk_test_… npx playwright test <spec> --project=chromium --retries=0`'
stamps = {
 '4.1': ('**5** ↑ (T3)', "**owner-surfaces lane (Fable gate) 2026-09-12:** rung-5 reachability — `e2e/journeys/dispatch-board.spec.ts` drives the real `/dispatch` page for two tenants in one run: owner A (Etc/UTC) sees exactly its 2 today jobs and not tomorrow's; owner B on America/Los_Angeles with a 23:00-local job sees it on B's own board (stored 06:00Z next day) while A's board is unchanged; B's job never appears on A's board. Hermetic Playwright at a real Postgres testcontainer — jobs via the real `POST /api/jobs`, no SQL setup, no admin route, no env shortcut; rows polled during the run. "+CMD+" → `dispatch-board` 1 passed (twice). Reachable + T3 → **5** (PR #1085)"),
 '4.2': ('**4−** ↑ (T2) reachable', "**owner-surfaces lane (Fable gate) 2026-09-12:** rung-5 reachability run — `e2e/journeys/dispatch-drag-proposal.spec.ts`: a real native drag on `/dispatch` creates a `draft` `reschedule_appointment` proposal and the `appointments` row is byte-identical before and after (polled); BOTH tenants drag in the same run, each gets exactly its own proposal in its own inbox and each appointment stays unchanged (T2). "+CMD+" → `dispatch-drag-proposal` 1 passed. Reachability and T2 proven; **5 withheld on the evidence class**: the product emits no `proposal.created` audit event for scheduling proposals (#1040), so the row stays REAL-DB-WRITE-ONLY 4− until that lands (PR #1085)"),
 '4.4': ('4', "**owner-surfaces lane (Fable gate) 2026-09-12:** rung-5 reachability NOT earned — `e2e/journeys/technician-day-view.spec.ts` proves the 23:00 America/Los_Angeles appointment lands on the tenant-local day (stored 06:00Z next day) through the owner's session, and that a technician session requesting tenant B's technician id is refused 403; but the technician's OWN day view is not reached: the hermetic api webServer forces `DEV_AUTH_BYPASS=true`, which skips the DB authorization loader, so `canonicalUserId` never resolves for an HMAC-verified technician and his own request 403s too (the page shows \"Failed to load appointments\"; pinned as a Playwright `test.fail()`; harness follow-up #1086). "+CMD+" → `technician-day-view` 1 passed + 1 expected fail. 4 (T1) stands (PR #1085)"),
 '1.2': ('**5** ↑ (T3)', "**owner-surfaces lane (Fable gate) 2026-09-12:** rung-5 reachability — `e2e/journeys/onboarding-identity.spec.ts` drives the real `/onboarding` identity form in the browser (business name, hourly rate, 42-mile radius) → `tenant_settings` row and `tenant.identity_set` audit row polled from real Postgres; the omit-tri-state (#874) driven at the same live `PUT /api/onboarding/identity` the form posts to (the form never omits the field) keeps 42; tenant B seeded first with different values (9900¢, 99 mi, America/Denver) is re-read unchanged at the end — two differently-configured tenants each correct in one run (T3). "+CMD+" → `onboarding-identity` 1 passed (twice). The second-tenant lane's neighbour leg in `onboarding-identity.test.ts` carries T1 at the integration seam. → **5** (PR #1085)"),
 '1.11': ('**5** ↑ (T2) / **3** (T1 FAILED — #1092)', "**owner-surfaces lane (Fable gate) 2026-09-12:** invite half — `e2e/journeys/accept-invitation.spec.ts` re-run at real Postgres (a pre-existing `blockExternalHosts` gap fixed in its first test): the invited technician follows the link and lands on his own day view; tenant B's real invitation token with a forged `tenant_id` claim joins tenant B, never A — two tenants' invitations resolve correctly in one run (T2) → **5**. Last-owner half — the sole owner's demotion is refused in the real `/settings` → Team members dialog (\"Cannot demote the only owner\"), `PATCH /api/users/:id` 400, `/api/me` unchanged: reached; but the T1 leg found the endpoint is NOT tenant-scoped — tenant A's owner PATCHing tenant B's owner id returned 200 and changed B's role (`PgUserRepository.update` has no tenant predicate): **SECURITY #1092**, fix lane launched, pinned as `test.fail()`. Isolation failed, so the second half holds at 3 until the fix merges (then 4, T1). "+CMD+" → `accept-invitation` 4 passed + 1 expected fail (PR #1085)"),
}
n=0
for key,(cell,note) in stamps.items():
    pat=re.compile(r'^(\| \*\*'+re.escape(key)+r'\*\* \|.*)$', re.M)
    m=pat.search(s); assert m, key
    line=m.group(1); cols=line.split(' | '); assert len(cols)>=5, (key,len(cols))
    cols[3]=cell
    last=cols[-1]; assert last.endswith(' |'), key
    cols[-1]=last[:-2]+' · '+note+' |'
    s=s[:m.start()]+' | '.join(cols)+s[m.end():]; n+=1
open(p,'w',encoding='utf-8').write(s); print('stamped',n,'rows')
